import { Service, ServiceStatus, ServiceType, User, Supplier, PaymentStatus } from './types';

export const ServiceColors: Record<ServiceType, string> = {
  [ServiceType.AIRPORT_TRANSFER]: 'bg-orange-100 text-orange-700 dark:bg-orange-900/50 dark:text-orange-300',
  [ServiceType.CITY_TOUR]: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300',
  [ServiceType.HOTEL_TRANSFER]: 'bg-sky-100 text-sky-700 dark:bg-sky-900/50 dark:text-sky-300',
  [ServiceType.WINE_TOUR]: 'bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300',
  [ServiceType.CUSTOM]: 'bg-slate-100 text-slate-700 dark:bg-slate-700/50 dark:text-slate-300',
};

export const ServiceBorderColors: Record<ServiceType, string> = {
    [ServiceType.AIRPORT_TRANSFER]: 'border-orange-500',
    [ServiceType.CITY_TOUR]: 'border-emerald-500',
    [ServiceType.HOTEL_TRANSFER]: 'border-sky-500',
    [ServiceType.WINE_TOUR]: 'border-purple-500',
    [ServiceType.CUSTOM]: 'border-slate-500',
};

// Added for theme customization
export const THEME_COLORS: Record<string, { main: string; hover: string; ring: string }> = {
    blue: { main: 'bg-blue-600', hover: 'hover:bg-blue-700', ring: 'focus:ring-blue-500' },
    indigo: { main: 'bg-indigo-600', hover: 'hover:bg-indigo-700', ring: 'focus:ring-indigo-500' },
    purple: { main: 'bg-purple-600', hover: 'hover:bg-purple-700', ring: 'focus:ring-purple-500' },
    green: { main: 'bg-green-600', hover: 'hover:bg-green-700', ring: 'focus:ring-green-500' },
};


const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);

const lastMonthDate = new Date(today.getFullYear(), today.getMonth() - 1, 1);
const nextMonthDate = new Date(today.getFullYear(), today.getMonth() + 1, 1);

const lastMonthYear = lastMonthDate.getFullYear();
const lastMonth = lastMonthDate.getMonth();

const nextMonthYear = nextMonthDate.getFullYear();
const nextMonth = nextMonthDate.getMonth();


export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    title: 'JFK Airport Pickup',
    clientName: 'John Doe',
    pickupAddress: 'John F. Kennedy International Airport, Queens, NY',
    dropoffAddress: '123 Main St, New York, NY',
    startTime: new Date(new Date().setHours(10, 0, 0, 0)),
    endTime: new Date(new Date().setHours(11, 0, 0, 0)),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    clientPrice: 150.00,
    driverId: 'driver1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    notes: 'Flight UA234, arriving at Terminal 4. Greet with a sign.',
    clientPaymentStatus: PaymentStatus.PAID,
    googleCalendarEventId: 'mock-gcal-1',
  },
  {
    id: '2',
    title: 'Manhattan City Tour',
    clientName: 'Jane Smith',
    pickupAddress: 'The Plaza Hotel, New York, NY',
    dropoffAddress: 'The Plaza Hotel, New York, NY',
    startTime: new Date(new Date().setHours(14, 0, 0, 0)),
    endTime: new Date(new Date().setHours(18, 0, 0, 0)),
    status: ServiceStatus.IN_PROGRESS,
    serviceType: ServiceType.CITY_TOUR,
    clientPrice: 400.00,
    driverId: 'driver2',
    createdById: 'partner1',
    numberOfPassengers: 4,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '3',
    title: 'Hotel Transfer',
    clientName: 'Peter Jones',
    pickupAddress: 'Marriott Marquis, New York, NY',
    dropoffAddress: 'LaGuardia Airport, Queens, NY',
    startTime: new Date(tomorrow.setHours(9, 30, 0, 0)),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.HOTEL_TRANSFER,
    clientPrice: 95.50,
    createdById: 'admin1',
    numberOfPassengers: 1,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '4',
    title: 'Napa Valley Wine Tour',
    clientName: 'Emily Williams',
    pickupAddress: 'San Francisco, CA',
    dropoffAddress: 'Napa Valley, CA',
    startTime: new Date(yesterday.setHours(9, 0, 0, 0)),
    endTime: new Date(yesterday.setHours(17, 0, 0, 0)),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.WINE_TOUR,
    clientPrice: 600.00,
    driverId: 'driver1',
    supplierId: 'supplier1',
    supplierCost: 350.00,
    createdById: 'partner1',
    numberOfPassengers: 3,
    clientPaymentStatus: PaymentStatus.PAID,
    supplierPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '5',
    title: 'Custom Transfer',
    clientName: 'Alice Johnson',
    pickupAddress: 'Grand Central Terminal, New York, NY',
    dropoffAddress: 'Newark Liberty International Airport, Newark, NJ',
    startTime: new Date(yesterday.setHours(15, 0, 0, 0)),
    endTime: new Date(yesterday.setHours(16, 30, 0, 0)),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 220.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 1,
    clientPaymentStatus: PaymentStatus.UNPAID, 
  },
  // --- PREVIOUS MONTH SERVICES ---
  {
    id: '6',
    title: 'Brooklyn Bridge Walk',
    clientName: 'Sarah Connor',
    pickupAddress: 'Brooklyn side of the bridge',
    dropoffAddress: 'Manhattan side of the bridge',
    startTime: new Date(lastMonthYear, lastMonth, 3, 13, 0),
    endTime: new Date(lastMonthYear, lastMonth, 3, 15, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CITY_TOUR,
    clientPrice: 120.00,
    driverId: 'driver1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '7',
    title: 'EWR Airport Dropoff',
    clientName: 'Carlos Ramirez',
    pickupAddress: '456 Park Ave, New York, NY',
    dropoffAddress: 'Newark Liberty International Airport, Newark, NJ',
    startTime: new Date(lastMonthYear, lastMonth, 5, 18, 30),
    endTime: new Date(lastMonthYear, lastMonth, 5, 19, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    clientPrice: 180.00,
    driverId: 'driver2',
    createdById: 'partner1',
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '8',
    title: 'Wine Tasting Getaway',
    clientName: 'Jessica Wong',
    pickupAddress: 'Jersey City, NJ',
    dropoffAddress: 'Long Island Wine Country',
    startTime: new Date(lastMonthYear, lastMonth, 8, 10, 0),
    endTime: new Date(lastMonthYear, lastMonth, 8, 18, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.WINE_TOUR,
    clientPrice: 750.00,
    supplierId: 'supplier2',
    supplierCost: 500,
    createdById: 'admin1',
    numberOfPassengers: 4,
    clientPaymentStatus: PaymentStatus.PAID,
    supplierPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '9',
    title: 'Corporate Transfer',
    clientName: 'Tech Solutions Inc.',
    pickupAddress: '1 Financial Square, New York, NY',
    dropoffAddress: 'JFK Airport',
    startTime: new Date(lastMonthYear, lastMonth, 10, 6, 0),
    endTime: new Date(lastMonthYear, lastMonth, 10, 7, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 250.00,
    driverId: 'driver1',
    createdById: 'admin1',
    numberOfPassengers: 3,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '10',
    title: 'LGA to Hotel',
    clientName: 'David Chen',
    pickupAddress: 'LaGuardia Airport',
    dropoffAddress: 'Hilton Midtown, New York, NY',
    startTime: new Date(lastMonthYear, lastMonth, 12, 21, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.HOTEL_TRANSFER,
    clientPrice: 110.00,
    driverId: 'driver2',
    createdById: 'partner1',
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '11',
    title: 'Museum Mile Tour',
    clientName: 'The Art Lovers',
    pickupAddress: 'Metropolitan Museum of Art',
    dropoffAddress: 'Guggenheim Museum',
    startTime: new Date(lastMonthYear, lastMonth, 15, 11, 0),
    endTime: new Date(lastMonthYear, lastMonth, 15, 15, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CITY_TOUR,
    clientPrice: 300.00,
    driverId: 'driver1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '12',
    title: 'Cancelled Booking',
    clientName: 'Unlucky Traveler',
    pickupAddress: 'Penn Station, New York, NY',
    dropoffAddress: 'JFK Airport',
    startTime: new Date(lastMonthYear, lastMonth, 18, 14, 0),
    status: ServiceStatus.CANCELLED,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    createdById: 'admin1',
  },
  {
    id: '13',
    title: 'Shopping Trip',
    clientName: 'Isabelle Dubois',
    pickupAddress: 'SoHo, New York, NY',
    dropoffAddress: 'Woodbury Common Premium Outlets',
    startTime: new Date(lastMonthYear, lastMonth, 20, 9, 0),
    endTime: new Date(lastMonthYear, lastMonth, 20, 17, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 550.00,
    driverId: 'driver2',
    createdById: 'partner1',
    numberOfPassengers: 3,
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '14',
    title: 'Late Night Pickup',
    clientName: 'Brian Miller',
    pickupAddress: 'JFK Airport',
    dropoffAddress: 'Brooklyn, NY',
    startTime: new Date(lastMonthYear, lastMonth, 22, 23, 30),
    endTime: new Date(lastMonthYear, lastMonth, 23, 0, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    clientPrice: 175.00,
    driverId: 'driver1',
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '15',
    title: 'Hotel Check-out',
    clientName: 'Kimberly Clark',
    pickupAddress: 'The Peninsula, New York, NY',
    dropoffAddress: 'EWR Airport',
    startTime: new Date(lastMonthYear, lastMonth, 28, 11, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.HOTEL_TRANSFER,
    clientPrice: 190.00,
    driverId: 'driver2',
    createdById: 'partner1',
    numberOfPassengers: 1,
    clientPaymentStatus: PaymentStatus.PAID,
  },

  // --- NEXT MONTH SERVICES ---
  {
    id: '16',
    title: 'Statue of Liberty Tour',
    clientName: 'The Walker Family',
    pickupAddress: 'Battery Park, New York, NY',
    dropoffAddress: 'Battery Park, New York, NY',
    startTime: new Date(nextMonthYear, nextMonth, 2, 9, 0),
    endTime: new Date(nextMonthYear, nextMonth, 2, 13, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.CITY_TOUR,
    clientPrice: 350.00,
    driverId: 'driver1',
    createdById: 'admin1',
    numberOfPassengers: 4,
    clientPaymentStatus: PaymentStatus.PARTIAL,
  },
  {
    id: '17',
    title: 'JFK Arrival',
    clientName: 'Hiro Tanaka',
    pickupAddress: 'JFK Airport',
    dropoffAddress: 'Park Hyatt, New York, NY',
    startTime: new Date(nextMonthYear, nextMonth, 4, 16, 0),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    clientPrice: 160.00,
    createdById: 'partner1',
    numberOfPassengers: 1,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '18',
    title: 'Concert at MSG',
    clientName: 'Alex Rodriguez',
    pickupAddress: 'Upper East Side, New York, NY',
    dropoffAddress: 'Madison Square Garden, New York, NY',
    startTime: new Date(nextMonthYear, nextMonth, 7, 18, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 100.00,
    driverId: 'driver2',
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '19',
    title: 'Hamptons Weekend',
    clientName: 'Olivia Preston',
    pickupAddress: 'Manhattan, New York, NY',
    dropoffAddress: 'East Hampton, NY',
    startTime: new Date(nextMonthYear, nextMonth, 10, 14, 0),
    endTime: new Date(nextMonthYear, nextMonth, 10, 16, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 450.00,
    driverId: 'driver1',
    createdById: 'partner1',
    numberOfPassengers: 3,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '20',
    title: 'Hudson Valley Tour',
    clientName: 'George Franklin',
    pickupAddress: 'Tarrytown, NY',
    dropoffAddress: 'Kykuit, the Rockefeller Estate',
    startTime: new Date(nextMonthYear, nextMonth, 12, 10, 0),
    endTime: new Date(nextMonthYear, nextMonth, 12, 16, 0),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.CITY_TOUR,
    clientPrice: 400.00,
    supplierId: 'supplier2',
    supplierCost: 250.00,
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.UNPAID,
    supplierPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '21',
    title: 'LGA Morning Flight',
    clientName: 'Samantha Bee',
    pickupAddress: 'Williamsburg, Brooklyn, NY',
    dropoffAddress: 'LaGuardia Airport',
    startTime: new Date(nextMonthYear, nextMonth, 15, 5, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.AIRPORT_TRANSFER,
    clientPrice: 90.00,
    driverId: 'driver2',
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '22',
    title: 'Wedding Guest Shuttle',
    clientName: 'Mr. & Mrs. Goldstein',
    pickupAddress: 'The Pierre Hotel',
    dropoffAddress: 'The Central Park Boathouse',
    startTime: new Date(nextMonthYear, nextMonth, 18, 16, 0),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 600.00,
    supplierId: 'supplier1',
    supplierCost: 400.00,
    createdById: 'partner1',
    numberOfPassengers: 10,
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '23',
    title: 'Newark Departure',
    clientName: 'Frank Reynolds',
    pickupAddress: 'SoHo Grand Hotel',
    dropoffAddress: 'Newark Liberty International Airport',
    startTime: new Date(nextMonthYear, nextMonth, 21, 13, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.HOTEL_TRANSFER,
    clientPrice: 185.00,
    driverId: 'driver1',
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
  {
    id: '24',
    title: 'Broadway Show Pickup',
    clientName: 'Angela Martin',
    pickupAddress: 'Richard Rodgers Theatre',
    dropoffAddress: 'West Village, New York, NY',
    startTime: new Date(nextMonthYear, nextMonth, 25, 22, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 85.00,
    driverId: 'driver2',
    createdById: 'partner1',
    numberOfPassengers: 2,
    clientPaymentStatus: PaymentStatus.PAID,
  },
  {
    id: '25',
    title: 'NJ Transit Connect',
    clientName: 'Kevin Malone',
    pickupAddress: 'Metropark Station, Iselin, NJ',
    dropoffAddress: 'Princeton, NJ',
    startTime: new Date(nextMonthYear, nextMonth, 28, 19, 0),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 130.00,
    createdById: 'admin1',
    clientPaymentStatus: PaymentStatus.UNPAID,
  },
];

export const MOCK_DRIVERS: User[] = [
    { id: 'driver1', name: 'Mike Johnson', email: 'mike@example.com', phone: '15551234567', role: 'DRIVER', availability: 'Available', photoUrl: 'https://randomuser.me/api/portraits/men/32.jpg' },
    { id: 'driver2', name: 'Sarah Chen', email: 'sarah@example.com', phone: '15557654321', role: 'DRIVER', availability: 'Busy', photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg' },
    { id: 'driver3', name: 'David Lee', email: 'david@example.com', phone: '15559876543', role: 'DRIVER', availability: 'On Leave', photoUrl: 'https://randomuser.me/api/portraits/men/36.jpg' },
];

export const MOCK_SUPPLIERS: Supplier[] = [
    { id: 'supplier1', name: 'Luxury Fleet Inc.', contactPerson: 'John Smith', email: 'john@luxury.com', phone: '15551112222' },
    { id: 'supplier2', name: 'Cityscape Tours LLC', contactPerson: 'Maria Garcia', email: 'maria@cityscape.com', phone: '15553334444' },
    { id: 'supplier3', name: 'Incomplete Buses Co.' },
];
