
import { Service, ServiceStatus, ServiceType, User, Supplier, PaymentStatus } from './types';

// User selectable colors for calendar events
export const EVENT_COLORS: Record<string, string> = {
  'Default': 'bg-blue-50 text-blue-900 border-blue-500 hover:bg-blue-100 dark:bg-blue-900/40 dark:text-blue-100 dark:border-blue-400 dark:hover:bg-blue-900/60',
  'Red': 'bg-red-50 text-red-900 border-red-500 hover:bg-red-100 dark:bg-red-900/40 dark:text-red-100 dark:border-red-400 dark:hover:bg-red-900/60',
  'Green': 'bg-green-50 text-green-900 border-green-500 hover:bg-green-100 dark:bg-green-900/40 dark:text-green-100 dark:border-green-400 dark:hover:bg-green-900/60',
  'Purple': 'bg-purple-50 text-purple-900 border-purple-500 hover:bg-purple-100 dark:bg-purple-900/40 dark:text-purple-100 dark:border-purple-400 dark:hover:bg-purple-900/60',
  'Orange': 'bg-orange-50 text-orange-900 border-orange-500 hover:bg-orange-100 dark:bg-orange-900/40 dark:text-orange-100 dark:border-orange-400 dark:hover:bg-orange-900/60',
  'Teal': 'bg-teal-50 text-teal-900 border-teal-500 hover:bg-teal-100 dark:bg-teal-900/40 dark:text-teal-100 dark:border-teal-400 dark:hover:bg-teal-900/60',
  'Gray': 'bg-slate-100 text-slate-900 border-slate-500 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-500 dark:hover:bg-slate-700',
  'Yellow': 'bg-yellow-50 text-yellow-900 border-yellow-500 hover:bg-yellow-100 dark:bg-yellow-900/40 dark:text-yellow-100 dark:border-yellow-400 dark:hover:bg-yellow-900/60',
  'Black': 'bg-black text-white border-slate-800 hover:bg-slate-900 dark:bg-slate-950 dark:text-slate-100 dark:border-slate-600 dark:hover:bg-slate-900',
};

// Modern Palette for Service Types
export const ServiceColors: Record<ServiceType, string> = {
  [ServiceType.TRANSFER]: 'bg-indigo-100 text-indigo-800 border-indigo-500 hover:bg-indigo-200 dark:bg-indigo-900/50 dark:text-indigo-200 dark:border-indigo-400',
  [ServiceType.TRANSFER_WITH_STOP]: 'bg-sky-100 text-sky-800 border-sky-500 hover:bg-sky-200 dark:bg-sky-900/50 dark:text-sky-200 dark:border-sky-400',
  [ServiceType.TOUR]: 'bg-emerald-100 text-emerald-800 border-emerald-500 hover:bg-emerald-200 dark:bg-emerald-900/50 dark:text-emerald-200 dark:border-emerald-400',
  [ServiceType.CUSTOM]: 'bg-slate-100 text-slate-800 border-slate-500 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-500',
};

// Helper to get just the border color class for specific uses
export const ServiceBorderColors: Record<ServiceType, string> = {
    [ServiceType.TRANSFER]: 'border-indigo-500 dark:border-indigo-400',
    [ServiceType.TRANSFER_WITH_STOP]: 'border-sky-500 dark:border-sky-400',
    [ServiceType.TOUR]: 'border-emerald-500 dark:border-emerald-400',
    [ServiceType.CUSTOM]: 'border-slate-500 dark:border-slate-400',
};

// Added for theme customization
export const THEME_COLORS: Record<string, { main: string; hover: string; ring: string }> = {
    blue: { main: 'bg-blue-600', hover: 'hover:bg-blue-700', ring: 'focus:ring-blue-500' },
    indigo: { main: 'bg-indigo-600', hover: 'hover:bg-indigo-700', ring: 'focus:ring-indigo-500' },
    purple: { main: 'bg-purple-600', hover: 'hover:bg-purple-700', ring: 'focus:ring-purple-500' },
    green: { main: 'bg-green-600', hover: 'hover:bg-green-700', ring: 'focus:ring-green-500' },
    red: { main: 'bg-red-600', hover: 'hover:bg-red-700', ring: 'focus:ring-red-500' },
    orange: { main: 'bg-orange-600', hover: 'hover:bg-orange-700', ring: 'focus:ring-orange-500' },
    amber: { main: 'bg-amber-600', hover: 'hover:bg-amber-700', ring: 'focus:ring-amber-500' },
    teal: { main: 'bg-teal-600', hover: 'hover:bg-teal-700', ring: 'focus:ring-teal-500' },
    cyan: { main: 'bg-cyan-600', hover: 'hover:bg-cyan-700', ring: 'focus:ring-cyan-500' },
    rose: { main: 'bg-rose-600', hover: 'hover:bg-rose-700', ring: 'focus:ring-rose-500' },
    slate: { main: 'bg-slate-600', hover: 'hover:bg-slate-700', ring: 'focus:ring-slate-500' },
};


const today = new Date();
const currentYear = today.getFullYear();

// Helper to generate specific dates in the current year
// Month is 0-indexed (0=Jan, 10=Nov, 11=Dec)
const getDate = (month: number, day: number, hour: number = 12, minute: number = 0) => {
    return new Date(currentYear, month, day, hour, minute);
};

export const MOCK_SERVICES: Service[] = [
  // --- NOVEMBER ---
  {
    id: 'nov-01',
    title: 'Arrival: British Airways BA112',
    clientName: 'Elena Rossi',
    pickupAddress: 'JFK Terminal 7',
    dropoffAddress: 'The Pierre Hotel, NY',
    startTime: getDate(10, 1, 14, 30),
    endTime: getDate(10, 1, 16, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 220.00,
    supplierCost: 70.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    passengersKids: 0,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-02',
    title: 'City Tour: Midtown Highlights',
    clientName: 'Smith Family',
    pickupAddress: 'Marriott Marquis',
    dropoffAddress: 'Marriott Marquis',
    startTime: getDate(10, 2, 9, 0),
    endTime: getDate(10, 2, 13, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TOUR,
    clientPrice: 550.00,
    supplierCost: 150.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 2,
    passengersKids: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    color: 'Default'
  },
  {
    id: 'nov-03',
    title: 'Departure: EWR United',
    clientName: 'James Bond',
    pickupAddress: 'SoHo Grand Hotel',
    dropoffAddress: 'Newark Airport Terminal C',
    startTime: getDate(10, 3, 6, 0),
    endTime: getDate(10, 3, 7, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 180.00,
    supplierCost: 60.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 1,
    passengersAdults: 1,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-05',
    title: 'Transfer: LGA to Brooklyn',
    clientName: 'Sarah Jessica',
    pickupAddress: 'LGA Terminal B',
    dropoffAddress: '123 Bedford Ave, Brooklyn',
    startTime: getDate(10, 5, 11, 15),
    endTime: getDate(10, 5, 12, 15),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 130.00,
    supplierCost: 40.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Pay to the driver',
    color: 'Default'
  },
  {
    id: 'nov-07',
    title: 'Business Meeting: Hourly',
    clientName: 'Corp Execs LLC',
    pickupAddress: 'Midtown Hilton',
    dropoffAddress: 'Wall Street',
    startTime: getDate(10, 7, 8, 0),
    endTime: getDate(10, 7, 18, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 1200.00,
    supplierCost: 350.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 3,
    passengersAdults: 3,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },
  {
    id: 'nov-09',
    title: 'Woodbury Outlets Trip',
    clientName: 'Maria Gonzalez',
    pickupAddress: 'Times Square Hotel',
    dropoffAddress: 'Woodbury Common',
    startTime: getDate(10, 9, 9, 0),
    endTime: getDate(10, 9, 16, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER_WITH_STOP,
    clientPrice: 600.00,
    supplierCost: 150.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 4,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-12',
    title: 'JFK to Greenwich CT',
    clientName: 'Hedge Fund Manager',
    pickupAddress: 'JFK Private Jet Center',
    dropoffAddress: 'Greenwich, CT',
    startTime: getDate(10, 12, 19, 0),
    endTime: getDate(10, 12, 20, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 450.00,
    supplierCost: 120.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 1,
    passengersAdults: 1,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },
  {
    id: 'nov-14',
    title: 'Dinner Transfer',
    clientName: 'The Davidsons',
    pickupAddress: 'Upper West Side',
    dropoffAddress: 'Carbone, NYC',
    startTime: getDate(10, 14, 18, 45),
    endTime: getDate(10, 14, 19, 15),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 150.00,
    supplierCost: 40.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-16',
    title: 'Full Day Disposal',
    clientName: 'Japanese Delegation',
    pickupAddress: 'UN Plaza',
    dropoffAddress: 'UN Plaza',
    startTime: getDate(10, 16, 8, 0),
    endTime: getDate(10, 16, 20, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 1500.00,
    supplierCost: 400.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 5,
    passengersAdults: 5,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },
  {
    id: 'nov-19',
    title: 'EWR Arrival: LH402',
    clientName: 'Klaus Weber',
    pickupAddress: 'Newark Airport',
    dropoffAddress: 'Jersey City Hyatt',
    startTime: getDate(10, 19, 15, 20),
    endTime: getDate(10, 19, 16, 15),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 160.00,
    supplierCost: 50.00,
    supplierId: 'supplier1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    supplierPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-22',
    title: 'Transfer: Philadelphia to NYC',
    clientName: 'Tech Startup Team',
    pickupAddress: 'Philadelphia Downtown',
    dropoffAddress: 'WeWork Chelsea',
    startTime: getDate(10, 22, 8, 30),
    endTime: getDate(10, 22, 10, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 550.00,
    supplierCost: 180.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 3,
    passengersAdults: 3,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-24',
    title: 'Thanksgiving Airport Drop',
    clientName: 'Family Gathering',
    pickupAddress: 'Westchester, NY',
    dropoffAddress: 'JFK Terminal 4',
    startTime: getDate(10, 24, 10, 0),
    endTime: getDate(10, 24, 11, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 300.00,
    supplierCost: 90.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 6,
    passengersAdults: 4,
    passengersKids: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    color: 'Default'
  },
  {
    id: 'nov-26',
    title: 'Black Friday Shopping',
    clientName: 'Shopping Group',
    pickupAddress: 'Sheraton Times Square',
    dropoffAddress: 'Garden State Plaza',
    startTime: getDate(10, 26, 8, 0),
    endTime: getDate(10, 26, 17, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER_WITH_STOP,
    clientPrice: 750.00,
    supplierCost: 200.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 4,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-28',
    title: 'JFK Arrival: AF006',
    clientName: 'Pierre Dubois',
    pickupAddress: 'JFK Terminal 1',
    dropoffAddress: 'Sofitel NYC',
    startTime: getDate(10, 28, 16, 45),
    endTime: getDate(10, 28, 18, 30),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 230.00,
    supplierCost: 75.00,
    supplierId: 'supplier2',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    supplierPaymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'nov-30',
    title: 'End of Month Meeting',
    clientName: 'CEO Transfer',
    pickupAddress: 'Greenwich Village',
    dropoffAddress: 'Teterboro Airport',
    startTime: getDate(10, 30, 14, 0),
    endTime: getDate(10, 30, 15, 0),
    status: ServiceStatus.COMPLETED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 250.00,
    supplierCost: 70.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 1,
    passengersAdults: 1,
    clientPaymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },

  // --- DECEMBER ---
  {
    id: 'dec-02',
    title: 'Holiday Lights Tour',
    clientName: 'Tourist Group A',
    pickupAddress: 'Rockefeller Center',
    dropoffAddress: 'Dyker Heights',
    startTime: getDate(11, 2, 17, 0),
    endTime: getDate(11, 2, 21, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TOUR,
    clientPrice: 450.00,
    supplierCost: 120.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 2,
    passengersKids: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-04',
    title: 'JFK Arrival: EK201',
    clientName: 'Ahmed Al-Fayed',
    pickupAddress: 'JFK Terminal 4',
    dropoffAddress: 'Mandarin Oriental',
    startTime: getDate(11, 4, 14, 20),
    endTime: getDate(11, 4, 16, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 250.00,
    supplierCost: 80.00,
    supplierId: 'supplier1',
    createdById: 'admin1',
    numberOfPassengers: 3,
    passengersAdults: 3,
    clientPaymentStatus: PaymentStatus.PAID,
    supplierPaymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-06',
    title: 'Corporate Party Shuttle',
    clientName: 'Finance Bros Inc',
    pickupAddress: 'Wall Street HQ',
    dropoffAddress: 'Cipriani 42nd St',
    startTime: getDate(11, 6, 18, 0),
    endTime: getDate(11, 6, 19, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 350.00,
    supplierCost: 100.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 6,
    passengersAdults: 6,
    clientPaymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },
  {
    id: 'dec-08',
    title: 'Departure: LGA Delta',
    clientName: 'Susan Miller',
    pickupAddress: 'Upper East Side',
    dropoffAddress: 'LGA Terminal C',
    startTime: getDate(11, 8, 10, 30),
    endTime: getDate(11, 8, 11, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 140.00,
    supplierCost: 40.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    color: 'Default'
  },
  {
    id: 'dec-10',
    title: 'Museum Tour',
    clientName: 'School Group',
    pickupAddress: 'Met Museum',
    dropoffAddress: 'Natural History Museum',
    startTime: getDate(11, 10, 10, 0),
    endTime: getDate(11, 10, 14, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TOUR,
    clientPrice: 600.00,
    supplierCost: 200.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 6,
    passengersAdults: 2,
    passengersKids: 4,
    clientPaymentStatus: PaymentStatus.PARTIAL,
    deposit: 100.00,
    paymentMethod: 'Paid deposit + balance to the driver',
    color: 'Default'
  },
  {
    id: 'dec-12',
    title: 'EWR Arrival: UA99',
    clientName: 'John Smith',
    pickupAddress: 'Newark Airport',
    dropoffAddress: 'Times Square',
    startTime: getDate(11, 12, 16, 45),
    endTime: getDate(11, 12, 18, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 185.00,
    supplierCost: 60.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-15',
    title: 'Holiday Shopping: 5th Ave',
    clientName: 'VIP Client',
    pickupAddress: 'The Plaza',
    dropoffAddress: 'Saks Fifth Ave',
    startTime: getDate(11, 15, 11, 0),
    endTime: getDate(11, 15, 15, 0),
    status: ServiceStatus.PENDING,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 500.00,
    supplierCost: 150.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.UNPAID,
    color: 'Default'
  },
  {
    id: 'dec-18',
    title: 'JFK Departure: Virgin',
    clientName: 'Emily Blunt',
    pickupAddress: 'Tribeca',
    dropoffAddress: 'JFK Terminal 4',
    startTime: getDate(11, 18, 15, 0),
    endTime: getDate(11, 18, 16, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 190.00,
    supplierCost: 65.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 1,
    passengersAdults: 1,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-20',
    title: 'Family Arrival: Christmas',
    clientName: 'The Griswolds',
    pickupAddress: 'LGA Terminal C',
    dropoffAddress: 'Connecticut',
    startTime: getDate(11, 20, 12, 30),
    endTime: getDate(11, 20, 14, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 350.00,
    supplierCost: 100.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 5,
    passengersAdults: 2,
    passengersKids: 3,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-22',
    title: 'City Transfer: Event',
    clientName: 'Event Planner',
    pickupAddress: 'Javits Center',
    dropoffAddress: 'Hudson Yards',
    startTime: getDate(11, 22, 17, 0),
    endTime: getDate(11, 22, 17, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 100.00,
    supplierCost: 30.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Future Invoice',
    color: 'Default'
  },
  {
    id: 'dec-24',
    title: 'Christmas Eve Dinner',
    clientName: 'High Net Worth Individual',
    pickupAddress: 'Park Ave Penthouse',
    dropoffAddress: 'Daniel',
    startTime: getDate(11, 24, 19, 0),
    endTime: getDate(11, 24, 22, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.CUSTOM,
    clientPrice: 600.00,
    supplierCost: 200.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-26',
    title: 'Boxing Day Tour',
    clientName: 'British Tourists',
    pickupAddress: 'Empire State Building',
    dropoffAddress: 'Statue of Liberty Ferry',
    startTime: getDate(11, 26, 9, 30),
    endTime: getDate(11, 26, 13, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TOUR,
    clientPrice: 500.00,
    supplierCost: 150.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 4,
    clientPaymentStatus: PaymentStatus.PAID,
    color: 'Default'
  },
  {
    id: 'dec-28',
    title: 'Departure: JFK',
    clientName: 'Returning Family',
    pickupAddress: 'Midtown Hotel',
    dropoffAddress: 'JFK Terminal 8',
    startTime: getDate(11, 28, 14, 0),
    endTime: getDate(11, 28, 15, 30),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 180.00,
    supplierCost: 60.00,
    driverId: 'driver2',
    createdById: 'admin1',
    numberOfPassengers: 3,
    passengersAdults: 2,
    passengersKids: 1,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  },
  {
    id: 'dec-29',
    title: 'Pre-NYE Arrival',
    clientName: 'Party Group',
    pickupAddress: 'LGA Terminal B',
    dropoffAddress: 'Meatpacking District',
    startTime: getDate(11, 29, 18, 0),
    endTime: getDate(11, 29, 19, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 160.00,
    supplierCost: 50.00,
    driverId: 'driver3',
    createdById: 'admin1',
    numberOfPassengers: 4,
    passengersAdults: 4,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Pay to the driver',
    color: 'Default'
  },
  {
    id: 'dec-31',
    title: 'NYE Gala Transfer',
    clientName: 'Celebrity Guest',
    pickupAddress: 'The Carlyle',
    dropoffAddress: 'Times Square Lockdown Zone',
    startTime: getDate(11, 31, 20, 0),
    endTime: getDate(11, 31, 21, 0),
    status: ServiceStatus.CONFIRMED,
    serviceType: ServiceType.TRANSFER,
    clientPrice: 500.00,
    supplierCost: 200.00,
    driverId: 'admin1',
    createdById: 'admin1',
    numberOfPassengers: 2,
    passengersAdults: 2,
    clientPaymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Prepaid',
    color: 'Default'
  }
];

export const MOCK_DRIVERS: User[] = [
    { id: 'admin1', name: 'Administrator (Me)', email: 'admin@example.com', phone: '15550000000', role: 'ADMIN', availability: 'Available', photoUrl: 'https://ui-avatars.com/api/?name=Admin+User&background=0D8ABC&color=fff' },
    { id: 'driver2', name: 'Sarah Chen', email: 'sarah@example.com', phone: '15557654321', role: 'DRIVER', availability: 'Busy', photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg' },
    { id: 'driver3', name: 'David Lee', email: 'david@example.com', phone: '15559876543', role: 'DRIVER', availability: 'On Leave', photoUrl: 'https://randomuser.me/api/portraits/men/36.jpg' },
];

export const MOCK_SUPPLIERS: Supplier[] = [
    { id: 'supplier1', name: 'Luxury Fleet Inc.', contactPerson: 'John Smith', email: 'john@luxury.com', phone: '15551112222' },
    { id: 'supplier2', name: 'Cityscape Tours LLC', contactPerson: 'Maria Garcia', email: 'maria@cityscape.com', phone: '15553334444' },
    { id: 'supplier3', name: 'Incomplete Buses Co.' },
];
